version: "3"

networks:
  monitoring:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:

  eexporter:
    container_name: eexporter
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
     - '--es.uri=http://134.214.202.26:9201'
     - '--es.all'
     - '--es.cluster_settings'
     - '--es.indices'
     - '--es.indices_settings'
    restart: always
    networks:
      monitoring:
          ipv4_address: 172.20.0.5
    ports:
    - "9114:9114"
  
  prometheus:
    image: prom/prometheus:0.18.0
    container_name: prometheus
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
        - '-config.file=/etc/prometheus/prometheus.yml'
    networks:
      monitoring:
          ipv4_address: 172.20.0.6
    ports:
        - '9090:9090'

  grafana:
    image: grafana/grafana:6.1.6
    container_name: grafana
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    links:
        - prometheus
    networks:
      monitoring:
          ipv4_address: 172.20.0.7
    ports:
        - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana:rw
volumes:
  grafana-storage:
    external: true