# defines two scrapers
#   1. docker - which collects the metrics of docker 
#   2. eexporter - which collects the metrics of elasticsearch
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'lambda-monitor'
scrape_configs:
    - job_name: 'eexporter'
      target_groups:
          - targets: ['172.20.0.5:9114']