- name: verify httpbeat install folder
  stat:
    #path: /tmp/elk/httpbeat-{{ httpbeat.version }}-linux-x86_64
    path: /tmp/elk/httpbeat
  register: path

- name: create directory for httpbeat
  file:
    path: /tmp/elk/httpbeat
    state: directory
  when: not path.stat.exists


