- name: verify metricbeat install folder
  stat:
    path: /tmp/elk/metricbeat-{{ metricbeat.version }}-linux-x86_64
  register: path

#- debug: display path var
#      var: path

- name: download metricbeat 
  shell: wget https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ metricbeat.version }}-linux-x86_64.tar.gz
  when: not path.stat.exists

- name: unzip metricbeat package
  shell: tar -xzvf metricbeat-{{ metricbeat.version }}-linux-x86_64.tar.gz -C /tmp/elk
  when: not path.stat.exists

- name: delete archive metricbeat
  shell: rm -rf metricbeat-{{ metricbeat.version }}-linux-x86_64.tar.gz*
  when: not path.stat.exists

