- name: verify Kibana install folder
  stat:
    path: /tmp/elk/kibana-{{ kibana.version }}-linux-x86_64
  register: path

#- debug: display path var
#      var: path

- name: download kibana 
  shell: wget https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana.version }}-linux-x86_64.tar.gz
  when: not path.stat.exists

- name: unzip Kibana package
  shell: tar -xzvf kibana-{{ kibana.version }}-linux-x86_64.tar.gz -C /tmp/elk
  when: not path.stat.exists

- name: delete archive kibana
  shell: rm -rf kibana-{{ kibana.version }}-linux-x86_64.tar.gz*
  when: not path.stat.exists

